CREATE TABLE [dbo].[Banks] (
	[BankId] INT IDENTITY(0,1) NOT NULL,
	[Name] NVARCHAR(30) NULL,
	[TaxNumber] NVARCHAR(20) NOT NULL,
	
	CONSTRAINT [PK_Bank] PRIMARY KEY CLUSTERED ([BankId] ASC ),

	CONSTRAINT [UQ_Bank_Name] UNIQUE NONCLUSTERED ([Name] ASC)
);